#!/usr/bin/env python
# import sys
# from something import something

# Logging
import logging
log = logging.getLogger(__name__)

class ClassName(Action):
  '''
  What does this class do?
  '''
  def __init__(self, f1):
    self.f1 = f1

  def doSomething(self):
    print("doSomething")

if __name__ == "__main__":
  ClassName().doSomething()