#!/usr/bin/perl
my $dirToBeAdded = shift;
my $dirHistoryFile = $ENV{"HOME"}."/.dirhistory";

# Create the directory history file if it does not exist
if (! -e $dirHistoryFile) {
	open DH, ">$dirHistoryFile" || die;
	close DH;
}

# Store the directories
my @dirs;

# Read the contents of ~/.dirhistory file
open DH2, "<$dirHistoryFile" || die "Cannot open $dirHistoryFile: $!";

# Recreate the list
while(my $dir = <DH2>) {
	chomp($dir);
	if ($dir ne $dirToBeAdded) {
		push(@dirs, $dir);		
	}
}
close DH2;

# Add the current directory to the end of the list
push(@dirs, $dirToBeAdded);

# Overwrite the directory history file with the updated list
open DH3, ">$dirHistoryFile" or die "Could not open file '$dirHistoryFile' $!";
my $i = 0;
while ($i<=$#dirs) {
    print DH3 "$dirs[$i]\n";
    $i++;
}
close DH3;

