#!/usr/bin/env perl

# Script that can be used in pipe

# Hash used to kept for uniqueness
my %unique_lines;

# The following line allows piped input
# Each line of input will be pushed to the hash 
# Sample line for bbh ouput
#    1480) [full docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow 1861 1507385410 /dev/ttys000]
#
# TODO grab the last line and show the command, it may not be complete 
#
while (<>) {
   if (/^\s*(\d+)\)\s+\[full\s+(.*?) \d+ \d+ [\/\w]+\]/) {
      $unique_lines{$2} = $1; 
   }
}

for my $k (sort { $unique_lines{$a} <=> $unique_lines{$b} } keys %unique_lines) {
    print "$unique_lines{$k} $k\n";
}

