#!/usr/bin/env perl

use File::Spec;
use File::Basename;

my $command;
my $file      = shift;
my $locater   = 'locate';

# Look for exact match
$command = "$locater $file | grep $file\$";

open( PIPE, "$command |" ) || die "Sorry, I couldn't open pipe.\n";
while (<PIPE>) {
    chomp($_);
    push( @list, $_ );
}
close PIPE;

my $fullname =  &getPick( \@list );

# Remove the file from the choice
print dirname($fullname);


# Print an interactive choice from a given list
sub getPick {
    my $ra_list = shift;
    if ( $#{$ra_list} > 0 ) {
        print STDERR "List:\n";
        for ( my $i = 0 ; $i <= $#{$ra_list} ; $i++ ) {
            print STDERR ( $i + 1 );
            print STDERR ") $$ra_list[$i]\n";
        }
        print STDERR "Make your choice\n";
        my $choice = <>;
        if ( $choice =~ /\d+/ ) {
            return $$ra_list[ $choice - 1 ];
        }
    }
    elsif ( $#{$ra_list} == 0 ) {
        return $$ra_list[0];
    }
    else {
        print STDERR "No list\n";
    }
    return 808;
}
