#!/usr/bin/env perl

my $file = shift;

open FILE_WITH_LIST, "<$file" || die "Cannot open $file: $!";

# Print the list with index
my $count = 1;
while(my $item = <FILE_WITH_LIST>) {
	print "$count) $item";
	$count++;
}
close FILE_WITH_LIST;

